In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from PIL import Image
import cv2
import os

In [ ]:
IMG_DIR = '/content/drive/MyDrive/data3a/training/01-minor'

for img in os.listdir(IMG_DIR):
    img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)

    img_pil = Image.fromarray(img_array)
    img_28x28 = np.array(img_pil.resize((28, 28), Image.ANTIALIAS))

    img_array = (img_28x28.flatten())

    img_array  = img_array.reshape(-1,1).T

    with open('train_01_minor.csv', 'ab') as f:

        np.savetxt(f, img_array, delimiter=",")

In [ ]:
IMG_DIR = '/content/drive/MyDrive/data3a/training/02-moderate'

for img in os.listdir(IMG_DIR):
    img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)

    img_pil = Image.fromarray(img_array)
    img_28x28 = np.array(img_pil.resize((28, 28), Image.ANTIALIAS))

    img_array = (img_28x28.flatten())

    img_array  = img_array.reshape(-1,1).T

    with open('train_02_moderate.csv', 'ab') as f:

        np.savetxt(f, img_array, delimiter=",")

In [ ]:
IMG_DIR = '/content/drive/MyDrive/data3a/training/03-severe'

for img in os.listdir(IMG_DIR):
    img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)

    img_pil = Image.fromarray(img_array)
    img_28x28 = np.array(img_pil.resize((28, 28), Image.ANTIALIAS))

    img_array = (img_28x28.flatten())

    img_array  = img_array.reshape(-1,1).T

    with open('train_03_severe.csv', 'ab') as f:

        np.savetxt(f, img_array, delimiter=",")

In [ ]:
train_minor = pd.read_csv("train_01_minor.csv", header=None)

columnnames = {}
count = 0
for i in train_minor.columns:
  count += 1
  columnnames[i] = f"Pix_{count}"
train_minor.rename(columns = columnnames ,inplace = True)

train_minor['label'] = 0
train_minor.head()





Pix_1  Pix_2  Pix_3  Pix_4  Pix_5  Pix_6  Pix_7  Pix_8  Pix_9  Pix_10  ...  \
0  165.0  165.0  164.0  165.0  166.0  162.0  203.0  150.0  152.0   171.0  ...   
1   60.0   77.0  103.0  115.0  143.0  144.0  148.0  152.0  154.0   155.0  ...   
2  171.0  207.0  150.0  114.0  142.0  121.0   97.0   50.0   51.0    61.0  ...   
3  117.0  115.0  112.0  111.0  108.0  105.0   97.0   76.0   64.0    56.0  ...   
4  107.0  105.0   98.0  113.0  116.0  107.0  109.0  115.0  105.0   114.0  ...   

   Pix_776  Pix_777  Pix_778  Pix_779  Pix_780  Pix_781  Pix_782  Pix_783  \
0     98.0     96.0     94.0    114.0    124.0    128.0    100.0    106.0   
1    121.0    123.0    116.0    111.0    112.0    105.0    106.0    102.0   
2    104.0    104.0    106.0    111.0    112.0    111.0    116.0    114.0   
3     47.0     57.0     76.0     93.0     87.0     81.0     96.0    138.0   
4     42.0     43.0     45.0     48.0     46.0     47.0    104.0    126.0   

   Pix_784  label  
0     93.0      0  
1     99.0      0  
2    115.0      0  
3    190.0      0  
4    118.0      0  

[5 rows x 785 columns]

In [ ]:
train_moderate = pd.read_csv("train_02_moderate.csv", header=None)

columnnames = {}
count = 0
for i in train_moderate.columns:
  count += 1
  columnnames[i] = f"Pix_{count}"
train_moderate.rename(columns = columnnames ,inplace = True)


train_moderate['label'] = 1
train_moderate.head()

Pix_1  Pix_2  Pix_3  Pix_4  Pix_5  Pix_6  Pix_7  Pix_8  Pix_9  Pix_10  ...  \
0  231.0  219.0  214.0  218.0  187.0  166.0  169.0  153.0  127.0   118.0  ...   
1  234.0  225.0  240.0  225.0  236.0  249.0  176.0  126.0  171.0   171.0  ...   
2  249.0  251.0  255.0  255.0  255.0  250.0  249.0  252.0  255.0   255.0  ...   
3  231.0  224.0  211.0  232.0  230.0  243.0  233.0  230.0  249.0   247.0  ...   
4  108.0   86.0  145.0  120.0   77.0   45.0   50.0   95.0   51.0    17.0  ...   

   Pix_776  Pix_777  Pix_778  Pix_779  Pix_780  Pix_781  Pix_782  Pix_783  \
0    132.0    134.0    135.0    125.0    119.0    113.0    113.0    116.0   
1    147.0    163.0    175.0    189.0    205.0    212.0    227.0    228.0   
2     78.0     81.0    194.0    255.0    236.0    218.0    194.0    183.0   
3     60.0     57.0     55.0     54.0     57.0     55.0     56.0     49.0   
4      9.0     29.0     47.0     17.0      9.0     20.0      5.0      2.0   

   Pix_784  label  
0    110.0      1  
1    222.0      1  
2    176.0      1  
3     43.0      1  
4      8.0      1  

[5 rows x 785 columns]

In [ ]:
train_severe = pd.read_csv("train_03_severe.csv", header=None)

columnnames = {}
count = 0
for i in train_severe.columns:
  count += 1
  columnnames[i] = f"Pix_{count}"
train_severe.rename(columns = columnnames ,inplace = True)

train_severe['label'] = 3
train_severe.head()

Pix_1  Pix_2  Pix_3  Pix_4  Pix_5  Pix_6  Pix_7  Pix_8  Pix_9  Pix_10  ...  \
0  155.0  176.0  204.0  202.0  208.0  212.0  208.0  203.0  204.0   210.0  ...   
1  246.0  249.0  249.0  248.0  251.0  241.0  191.0  192.0  191.0   194.0  ...   
2  200.0  227.0  207.0  156.0  171.0  155.0   87.0   86.0   85.0    81.0  ...   
3  160.0  169.0  143.0   98.0  126.0  137.0  145.0  134.0  121.0   136.0  ...   
4   15.0   39.0   34.0   45.0   81.0  142.0  150.0  125.0  107.0    69.0  ...   

   Pix_776  Pix_777  Pix_778  Pix_779  Pix_780  Pix_781  Pix_782  Pix_783  \
0     64.0     48.0     36.0     28.0     38.0     38.0     44.0     87.0   
1     74.0     78.0     73.0     71.0     68.0     69.0     81.0     73.0   
2    122.0    123.0    125.0    130.0    125.0    128.0    138.0    141.0   
3    208.0    244.0    245.0    246.0    246.0    246.0    246.0    247.0   
4    255.0    255.0    255.0    255.0    255.0    255.0    255.0    255.0   

   Pix_784  label  
0    117.0      3  
1     66.0      3  
2    147.0      3  
3    246.0      3  
4    255.0      3  

[5 rows x 785 columns]

In [ ]:
data=pd.concat([train_minor,train_moderate,train_severe])
data.shape

(1383, 785)

In [ ]:
X_train=data.iloc[:,:-1]
X_train.shape

(1383, 784)

In [ ]:
y_train=data.iloc[:,-1]
y_train.shape

(1383,)

In [58]:
from sklearn.cluster import MiniBatchKMeans
import numpy as np

total_clusters = len(np.unique(y_train))
# Initialize the K-Means model
kmeans = MiniBatchKMeans(n_clusters = total_clusters)
# Fitting the model to training set
kmeans.fit(X_train)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


MiniBatchKMeans(n_clusters=3)

In [60]:
kmeans.labels_

array([2, 1, 1, ..., 0, 1, 1], dtype=int32)

In [62]:
def retrieve_info(cluster_labels,y_train):
  '''
  Associates most probable label with each cluster in KMeans model
  returns: dictionary of clusters assigned to each label
  '''
  # Initializing

  reference_labels = {}
  # For loop to run through each label of cluster label
  for i in range(len(np.unique(kmeans.labels_))):
    
    index = np.where(cluster_labels == i,1,0)
    num = np.bincount(y_train[index==1]).argmax()
    reference_labels[i] = num

  
  return reference_labels


In [63]:
reference_labels = retrieve_info(kmeans.labels_,y_train)
number_labels = np.random.rand(len(kmeans.labels_))
for i in range(len(kmeans.labels_)):
  number_labels[i] = reference_labels[kmeans.labels_[i]]

In [64]:
reference_labels = retrieve_info(kmeans.labels_,y_train)
number_labels = np.random.rand(len(kmeans.labels_))
for i in range(len(kmeans.labels_)):
  number_labels[i] = reference_labels[kmeans.labels_[i]]

In [65]:
y_train=y_train.to_numpy()


AttributeError: ignored

In [66]:
# Comparing Predicted values and Actual values
print(number_labels[:20].astype(int))
print(y_train[:20])

[3 1 1 3 1 3 3 3 3 1 3 3 1 3 3 3 3 3 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [67]:
type(number_labels), type(y_train)

(numpy.ndarray, numpy.ndarray)

In [68]:
# Calculating accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(number_labels,y_train))

0.3492407809110629


In [69]:
# Function to calculate metrics for the model
import sklearn.metrics as metrics

def calculate_metrics(model,output):
  print('Number of clusters is {}'.format(model.n_clusters))
  print('Inertia : {}'.format(model.inertia_))
  print('Homogeneity :       {}'.format(metrics.homogeneity_score(output,model.labels_)))




In [70]:
cluster_number = [10,16,36,64,144,256]
for i in cluster_number:
  total_clusters = len(np.unique(y_train))
# Initialize the K-Means model
  kmeans = MiniBatchKMeans(n_clusters = i)
# Fitting the model to training set
  kmeans.fit(X_train)
# Calculating the metrics
 
  calculate_metrics(kmeans,y_train)
# Calculating reference_labels
  reference_labels = retrieve_info(kmeans.labels_,y_train)
# ‘number_labels’ is a list which denotes the number displayed in image
  number_labels = np.random.rand(len(kmeans.labels_))

  for i in range(len(kmeans.labels_)):
 
    number_labels[i] = reference_labels[kmeans.labels_[i]]
 
  print('Accuracy score : {}'.format(accuracy_score(number_labels,y_train)))
  print('\n')

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 10
Inertia : 3138554509.0080276
Homogeneity :       0.01666535665503746
Accuracy score : 0.3933477946493131




/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 16
Inertia : 2974500160.2631006
Homogeneity :       0.01802547217637388
Accuracy score : 0.39117859725235




/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 36
Inertia : 2758974698.6529694
Homogeneity :       0.04074554729993197
Accuracy score : 0.42733188720173537




/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 64
Inertia : 2601150976.5449514
Homogeneity :       0.06529224575203443
Accuracy score : 0.44685466377440347




/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 144
Inertia : 2291656158.6683354
Homogeneity :       0.12887884023319424
Accuracy score : 0.4938539407086045




/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 256
Inertia : 2006325798.831439
Homogeneity :       0.2185176388552057
Accuracy score : 0.5502530730296457




In [46]:
cluster_number = [10,16,36,64,144,256]
for i in cluster_number:
  total_clusters = len(np.unique(y_train))
# Initialize the K-Means model
  kmeans = MiniBatchKMeans(n_clusters = i)
# Fitting the model to training set
  kmeans.fit(X_train)
# Calculating the metrics
 
  calculate_metrics(kmeans,y_train)
# Calculating reference_labels
  reference_labels = retrieve_info(kmeans.labels_,y_train)
# ‘number_labels’ is a list which denotes the number displayed in image
  number_labels = np.random.rand(len(kmeans.labels_))

for i in range(len(kmeans.labels_)):
 
 number_labels[i] = reference_labels[kmeans.labels_[i]]

print('Accuracy score : {}'.format(accuracy_score(number_labels,y_train)))
print('\n')

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 10
Inertia : 3109531646.9515033
Homogeneity :       0.01587782851947918


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 16
Inertia : 2982467677.724148
Homogeneity :       0.025340838303147796


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 36
Inertia : 2738881719.478958
Homogeneity :       0.04490793888893357


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 64
Inertia : 2612117555.8006773
Homogeneity :       0.06051179255768889


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 144
Inertia : 2282663981.250352
Homogeneity :       0.14241966801562878


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Number of clusters is 256
Inertia : 2000207172.5465293
Homogeneity :       0.20766653739114618


ValueError: ignored

In [47]:
# Testing model on Testing set
# Initialize the K-Means model
kmeans = MiniBatchKMeans(n_clusters = 256)
# Fitting the model to testing set
kmeans.fit(X_test)
# Calculating the metrics
calculate_metrics(kmeans,y_test)
# Calculating the reference_labels
reference_labels = retrieve_info(kmeans.labels_,y_test)
# ‘number_labels’ is a list which denotes the number displayed in image
number_labels = np.random.rand(len(kmeans.labels_))
for i in range(len(kmeans.labels_)):
 
 number_labels[i] = reference_labels[kmeans.labels_[i]]
 
print('Accuracy score : {}'.format(accuracy_score(number_labels,y_test)))
print('\n')

NameError: ignored